/* Auto-generated by genmsg_cpp for file /home/kauil/ros_workspace/odometry/msg/encoder.msg */
#ifndef ODOMETRY_MESSAGE_ENCODER_H
#define ODOMETRY_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace odometry
{
template <class ContainerAllocator>
struct encoder_ {
  typedef encoder_<ContainerAllocator> Type;

  encoder_()
  : rpulses(0.0)
  , lpulses(0.0)
  {
  }

  encoder_(const ContainerAllocator& _alloc)
  : rpulses(0.0)
  , lpulses(0.0)
  {
  }

  typedef double _rpulses_type;
  double rpulses;

  typedef double _lpulses_type;
  double lpulses;


private:
  static const char* __s_getDataType_() { return "odometry/encoder"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a066eb83358996063bdf035669876fc4"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 rpulses\n\
float64 lpulses\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, rpulses);
    ros::serialization::serialize(stream, lpulses);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, rpulses);
    ros::serialization::deserialize(stream, lpulses);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(rpulses);
    size += ros::serialization::serializationLength(lpulses);
    return size;
  }

  typedef boost::shared_ptr< ::odometry::encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::encoder_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct encoder
typedef  ::odometry::encoder_<std::allocator<void> > encoder;

typedef boost::shared_ptr< ::odometry::encoder> encoderPtr;
typedef boost::shared_ptr< ::odometry::encoder const> encoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::odometry::encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::odometry::encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace odometry

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::odometry::encoder_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::odometry::encoder_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::odometry::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a066eb83358996063bdf035669876fc4";
  }

  static const char* value(const  ::odometry::encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa066eb8335899606ULL;
  static const uint64_t static_value2 = 0x3bdf035669876fc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "odometry/encoder";
  }

  static const char* value(const  ::odometry::encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::odometry::encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 rpulses\n\
float64 lpulses\n\
\n\
";
  }

  static const char* value(const  ::odometry::encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::odometry::encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::odometry::encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.rpulses);
    stream.next(m.lpulses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::odometry::encoder_<ContainerAllocator> & v) 
  {
    s << indent << "rpulses: ";
    Printer<double>::stream(s, indent + "  ", v.rpulses);
    s << indent << "lpulses: ";
    Printer<double>::stream(s, indent + "  ", v.lpulses);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_ENCODER_H

